env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1"

window:
  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 10
    y: 10

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

scrolling:
  history: 2500
  multiplier: 3

font:
  normal:
    family: FiraMono Nerd Font
    style: Medium

  bold:
    family: FiraMono Nerd Font
    style: Bold

  italic:
    family: FiraMono Nerd Font
    style: Italic

  bold_italic:
    family: FiraMono Nerd Font
    style: Bold Italic

  size: 13

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  indexed_colors: []

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

background_opacity: 0.96

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

dynamic_title: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: false

working_directory: None

alt_send_esc: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

  url:
    launcher:
      program: xdg-open

    modifiers: None

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Add,      mods: Control,       action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Return,   mods: Alt,           action: ToggleFullscreen }
  - { key: Paste,                         action: Paste            }
  - { key: Copy,                          action: Copy             }
  - { key: L,        mods: Control,       action: ClearLogNotice   }
  - { key: L,        mods: Control,       chars: "\x0c"            }
  - { key: PageUp,   mods: Shift,         action: ScrollPageUp,   mode: ~Alt }
  - { key: PageDown, mods: Shift,         action: ScrollPageDown, mode: ~Alt }
  - { key: Home,     mods: Shift,         action: ScrollToTop,    mode: ~Alt }
  - { key: End,      mods: Shift,         action: ScrollToBottom, mode: ~Alt }

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
